# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_dcafe.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, images_rc

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1124, 721)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 1101, 701))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 30, 1041, 641))
        self.label.setStyleSheet("border-image: url(:/images/background.png);\n"
"border-radius: 20px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(80, 130, 561, 491))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.697, y1:0, x2:0.294, y2:0, stop:1 rgba(255, 201, 222, 173));\n"
"border-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(-350, 420, 861, 641))
        self.label_3.setStyleSheet("image: url(:/images/coffee beans_2.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(370, 270, 561, 461))
        self.label_4.setStyleSheet("image: url(:/images/coffee beans.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(640, -370, 861, 641))
        self.label_5.setStyleSheet("image: url(:/images/coffee beans_2.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(-20, 120, 211, 211))
        self.label_6.setStyleSheet("image: url(:/images/coffee beans.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(60, 30, 541, 191))
        self.label_8.setStyleSheet("font: 75 60pt \"Tw Cen MT\";\n"
"color: rgb(223, 107, 145);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setGeometry(QtCore.QRect(70, 40, 541, 191))
        self.label_9.setStyleSheet("font: 75 60pt \"Tw Cen MT\";\n"
"color: rgb(255, 239, 245);")
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setGeometry(QtCore.QRect(350, 160, 281, 61))
        self.label_11.setStyleSheet("font: 13pt \"Tw Cen MT\";\n"
"color: rgb(146, 86, 67);")
        self.label_11.setObjectName("label_11")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(420, 630, 41, 31))
        self.label_7.setStyleSheet("image: url(:/images/instagram icon.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setGeometry(QtCore.QRect(280, 620, 141, 51))
        self.label_12.setStyleSheet("font: 13pt \"Tw Cen MT\";\n"
"color: rgb(204, 0, 85);")
        self.label_12.setObjectName("label_12")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(570, 680, 321, 31))
        self.lineEdit_4.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(193, 193, 193);\n"
"color:rgba(255,255,255,230);\n"
"padding-bottom:7px;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setGeometry(QtCore.QRect(30, 220, 101, 101))
        self.label_10.setStyleSheet("image: url(:/images/coffee beans.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 240, 301, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(83, 51, 42);\n"
"color: rgb(98, 60, 50);\n"
"padding-bottom:7px;")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(83, 51, 42);\n"
"color: rgb(98, 60, 50);\n"
"padding-bottom:7px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(14)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(83, 51, 42);\n"
"color: rgb(98, 60, 50);\n"
"padding-bottom:7px;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(14)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(83, 51, 42);\n"
"color: rgb(98, 60, 50);\n"
"padding-bottom:7px;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(14)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgb(83, 51, 42);\n"
"color: rgb(98, 60, 50);\n"
"padding-bottom:7px;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout.addWidget(self.lineEdit_6)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(220, 530, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"background-color: rgb(137, 81, 62);\n"
"color: rgb(255, 239, 245);\n"
"border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"background-color: rgb(202, 148, 129);\n"
"color: rgb(255, 239, 245);\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color: rgb(231, 140, 169);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 530, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"font: 12pt \"Tw Cen MT\";\n"
"color: rgb(137, 81, 62);\n"
"text-decoration:underline;\n"
"border:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"color: rgb(202, 148, 129); /* Warna latar belakang saat hover */\n"
"}\n"
"\n"
"/* QPushButton Pressed State */\n"
"QPushButton:pressed {\n"
"color: rgb(231, 140, 169); /* Warna latar belakang saat tombol ditekan */\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_8.setText(_translate("Form", "Latte D\' Cafe"))
        self.label_9.setText(_translate("Form", "Latte D\' Cafe"))
        self.label_11.setText(_translate("Form", "developed by Karima A. Karim"))
        self.label_12.setText(_translate("Form", "@latte_d_cafe"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Name"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Order"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Amount"))
        self.lineEdit_5.setPlaceholderText(_translate("Form", "Note"))
        self.lineEdit_6.setPlaceholderText(_translate("Form", "Price"))
        self.pushButton.setText(_translate("Form", "Submit"))
        self.pushButton_2.setText(_translate("Form", " See order list"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())